In [1]:
from pycaret.regression import *
import pandas as pd

In [2]:
# Load the cleaned dataset
df = pd.read_csv('cleaned_melbourne_data.csv')

In [3]:

# Display dataset information
print("Dataset Overview:")
print(df.info())
print("\nFirst 5 Rows:")
print(df.head())

Dataset Overview:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  int64
 5   Method         13580 non-null  object
 6   Seller         13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  int64
 10  Bedroom2       13580 non-null  int64
 11  Bathroom       13580 non-null  int64
 12  Car            13580 non-null  float64
 13  Landsize       13580 non-null  int64
 14  BuildingArea   13580 non-null  float64
 15  YearBuilt      13580 non-null  float64
 16  Lattitude      13580 non-null  float64
 17  Longtitude     13580 non-null  float64
 18  Region         13580 non-null  object
 19  Propertycount  13580 non-null  int64
dtypes: float64(6), int64(7), object(7)
memory usage: 2.1+ MB
None

First 5 Rows:
         Suburb           Address  Rooms Type    Price Method         Seller  \
0  Airport West     154 Halsey Rd      3    t   840000     PI         Nelson
1   Albert Park    105 Kerferd Rd      2    h  1275000      S  hockingstuart
2   Albert Park  85 Richardson St      2    h  1455000      S        Thomson
3    Alphington        6 Smith St      4    h  2000000      S          Brace
4    Alphington   5/6 Yarralea St      3    h  1110000      S         Jellis

       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  \
0  3/9/2023      13.5      3042         3         2  1.0       303
1  3/9/2023       3.3      3206         2         1  0.0       120
2  3/9/2023       3.3      3206         2         1  0.0       159
3  3/9/2023       6.4      3078         3         2  4.0       853
4  3/9/2023       6.4      3078         3         2  2.0       208

   BuildingArea  YearBuilt  Lattitude  Longtitude                 Region  \
0         225.0     2016.0   -37.7180    144.8780   Western Metropolitan
1          82.0     1900.0   -37.8459    144.9555  Southern Metropolitan
2         126.0     1970.0   -37.8450    144.9538  Southern Metropolitan
3         263.0     1930.0   -37.7707    145.0318  Northern Metropolitan
4         126.0     2013.0   -37.7854    145.0325  Northern Metropolitan

   Propertycount
0           3464
1           3280
2           3280
3           2211
4           2211

In [4]:
# Set up the PyCaret regression environment
print("\nInitializing PyCaret Setup...")
exp = setup(df, target='Price', session_id=42, normalize=True, remove_multicollinearity=True, train_size=0.8)

Initializing PyCaret Setup...

In [5]:
# Compare multiple regression models and select top-performing ones
print("\nComparing Models...")
best_models = compare_models(n_select=5, sort='R2')
print("\nTop 5 Selected Models:")
print(best_models)

Comparing Models...

Top 5 Selected Models:
[KNeighborsRegressor(n_jobs=-1), ElasticNet(random_state=42), AdaBoostRegressor(random_state=42), XGBRegressor(base_score=None, booster='gbtree', callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cpu', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=-1,
             num_parallel_tree=None, random_state=42, ...), ExtraTreesRegressor(n_jobs=-1, random_state=42)]

In [6]:
# Tune hyperparameters of selected models
print("\nTuning Selected Models...")
tuned_models = []
for model in best_models:
    print(f"Tuning {model}")
    tuned_model = tune_model(model, optimize='R2')
    tuned_models.append(tuned_model)
    print(f"Best Tuned Model Parameters: {tuned_model}")

Tuning Selected Models...
Tuning KNeighborsRegressor(n_jobs=-1)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Best Tuned Model Parameters: KNeighborsRegressor(metric='manhattan', n_jobs=-1, n_neighbors=8)
Tuning ElasticNet(random_state=42)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).
Best Tuned Model Parameters: ElasticNet(random_state=42)
Tuning AdaBoostRegressor(random_state=42)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Best Tuned Model Parameters: AdaBoostRegressor(learning_rate=0.4, loss='square', n_estimators=210,
                  random_state=42)
Tuning XGBRegressor(base_score=None, booster='gbtree', callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cpu', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=-1,
             num_parallel_tree=None, random_state=42, ...)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Best Tuned Model Parameters: XGBRegressor(base_score=None, booster='gbtree', callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.5, device='cpu', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=8, max_leaves=None,
             min_child_weight=4, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=130, n_jobs=-1,
             num_parallel_tree=None, random_state=42, ...)
Tuning ExtraTreesRegressor(n_jobs=-1, random_state=42)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Best Tuned Model Parameters: ExtraTreesRegressor(max_depth=11, max_features='log2',
                    min_impurity_decrease=0.0001, min_samples_leaf=3,
                    min_samples_split=7, n_estimators=30, n_jobs=-1,
                    random_state=42)

In [7]:
# Evaluate each tuned model
print("\nEvaluating Models...")
for model in tuned_models:
    print(f"\nEvaluating {model}")
    evaluate_model(model)

Evaluating Models...

Evaluating KNeighborsRegressor(metric='manhattan', n_jobs=-1, n_neighbors=8)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

Evaluating ElasticNet(random_state=42)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

Evaluating AdaBoostRegressor(learning_rate=0.4, loss='square', n_estimators=210,
                  random_state=42)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

Evaluating XGBRegressor(base_score=None, booster='gbtree', callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.5, device='cpu', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=8, max_leaves=None,
             min_child_weight=4, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=130, n_jobs=-1,
             num_parallel_tree=None, random_state=42, ...)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

Evaluating ExtraTreesRegressor(max_depth=11, max_features='log2',
                    min_impurity_decrease=0.0001, min_samples_leaf=3,
                    min_samples_split=7, n_estimators=30, n_jobs=-1,
                    random_state=42)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [10]:
# Select the best model based on R2 score
best_model = tuned_models[0]  # The first model is the best one after sorting
print(f"\nFinalizing and Saving the Best Model: {best_model}")

# Finalize the best model
final_best_model = finalize_model(best_model)

# Save only the best model
save_model(final_best_model, 'C:/Users/srira/OneDrive/MLOPS/individual/models')

print("\n✅ Best Model Saved Successfully!")

Finalizing and Saving the Best Model: KNeighborsRegressor(metric='manhattan', n_jobs=-1, n_neighbors=8)
Transformation Pipeline and Model Successfully Saved

✅ Best Model Saved Successfully!

In [ ]:
print("\nModel training and saving completed successfully.")

In [2]:
from pycaret.regression import load_model

model = load_model("C:/Users/srira/OneDrive/MLOPS/individual/model/final_model_1")
print(model)

Transformation Pipeline and Model Successfully Loaded
Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(include=['Rooms', 'Distance', 'Postcode',
                                             'Bedroom2', 'Bathroom', 'Car',
                                             'Landsize', 'BuildingArea',
                                             'YearBuilt', 'Lattitude',
                                             'Longtitude', 'Propertycount'],
                                    transformer=SimpleImputer())),
                ('categorical_imputer',
                 TransformerWrapper(include=['Suburb', 'Address', 'Type',
                                             'Method', 'S...
                                    transformer=TargetEncoder(cols=['Suburb',
                                                                    'Address',
                                                                    'Seller',
                                                                    'Date'],
                                                              handle_missing='return_nan'))),
                ('remove_multicollinearity',
                 TransformerWrapper(exclude=[],
                                    transformer=RemoveMulticollinearity(threshold=0.9))),
                ('normalize', TransformerWrapper(transformer=StandardScaler())),
                ('actual_estimator',
                 KNeighborsRegressor(metric='manhattan', n_jobs=-1,
                                     n_neighbors=8))])